// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: progress.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 進捗タイプ
type ProgressType int32

const (
	ProgressType_PROGRESS_TYPE_UNSPECIFIED ProgressType = 0
	ProgressType_PROGRESS_TYPE_STARTED     ProgressType = 1 // 開始
	ProgressType_PROGRESS_TYPE_PROGRESS    ProgressType = 2 // 進行中
	ProgressType_PROGRESS_TYPE_COMPLETE    ProgressType = 3 // 完了
	ProgressType_PROGRESS_TYPE_ERROR       ProgressType = 4 // エラー
)

// Enum value maps for ProgressType.
var (
	ProgressType_name = map[int32]string{
		0: "PROGRESS_TYPE_UNSPECIFIED",
		1: "PROGRESS_TYPE_STARTED",
		2: "PROGRESS_TYPE_PROGRESS",
		3: "PROGRESS_TYPE_COMPLETE",
		4: "PROGRESS_TYPE_ERROR",
	}
	ProgressType_value = map[string]int32{
		"PROGRESS_TYPE_UNSPECIFIED": 0,
		"PROGRESS_TYPE_STARTED":     1,
		"PROGRESS_TYPE_PROGRESS":    2,
		"PROGRESS_TYPE_COMPLETE":    3,
		"PROGRESS_TYPE_ERROR":       4,
	}
)

func (x ProgressType) Enum() *ProgressType {
	p := new(ProgressType)
	*p = x
	return p
}

func (x ProgressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgressType) Descriptor() protoreflect.EnumDescriptor {
	return file_progress_proto_enumTypes[0].Descriptor()
}

func (ProgressType) Type() protoreflect.EnumType {
	return &file_progress_proto_enumTypes[0]
}

func (x ProgressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProgressType.Descriptor instead.
func (ProgressType) EnumDescriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{0}
}

// 進捗ストリームリクエスト
type StreamProgressRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 特定のジョブIDを指定（空の場合はすべての進捗を受信）
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProgressRequest) Reset() {
	*x = StreamProgressRequest{}
	mi := &file_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProgressRequest) ProtoMessage() {}

func (x *StreamProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProgressRequest.ProtoReflect.Descriptor instead.
func (*StreamProgressRequest) Descriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{0}
}

func (x *StreamProgressRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// 進捗更新メッセージ
type ProgressUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 進捗タイプ
	Type ProgressType `protobuf:"varint,1,opt,name=type,proto3,enum=desktop_server.v1.ProgressType" json:"type,omitempty"`
	// メッセージ
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 現在のステップ
	CurrentStep int32 `protobuf:"varint,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	// 総ステップ数
	TotalSteps int32 `protobuf:"varint,4,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	// 進捗率（0-100）
	Percentage int32 `protobuf:"varint,5,opt,name=percentage,proto3" json:"percentage,omitempty"`
	// 関連するジョブID（ある場合）
	JobId string `protobuf:"bytes,6,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// タイムスタンプ
	Timestamp     int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{1}
}

func (x *ProgressUpdate) GetType() ProgressType {
	if x != nil {
		return x.Type
	}
	return ProgressType_PROGRESS_TYPE_UNSPECIFIED
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdate) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *ProgressUpdate) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *ProgressUpdate) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ProgressUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProgressUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_progress_proto protoreflect.FileDescriptor

const file_progress_proto_rawDesc = "" +
	"\n" +
	"\x0eprogress.proto\x12\x11desktop_server.v1\".\n" +
	"\x15StreamProgressRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xf8\x01\n" +
	"\x0eProgressUpdate\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.desktop_server.v1.ProgressTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\x05R\vcurrentStep\x12\x1f\n" +
	"\vtotal_steps\x18\x04 \x01(\x05R\n" +
	"totalSteps\x12\x1e\n" +
	"\n" +
	"percentage\x18\x05 \x01(\x05R\n" +
	"percentage\x12\x15\n" +
	"\x06job_id\x18\x06 \x01(\tR\x05jobId\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp*\x99\x01\n" +
	"\fProgressType\x12\x1d\n" +
	"\x19PROGRESS_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROGRESS_TYPE_STARTED\x10\x01\x12\x1a\n" +
	"\x16PROGRESS_TYPE_PROGRESS\x10\x02\x12\x1a\n" +
	"\x16PROGRESS_TYPE_COMPLETE\x10\x03\x12\x17\n" +
	"\x13PROGRESS_TYPE_ERROR\x10\x042z\n" +
	"\x0fProgressService\x12g\n" +
	"\x16StreamDownloadProgress\x12(.desktop_server.v1.StreamProgressRequest\x1a!.desktop_server.v1.ProgressUpdate0\x01B=Z;github.com/yhonda-ohishi-pub-dev/desktop-server/proto;protob\x06proto3"

var (
	file_progress_proto_rawDescOnce sync.Once
	file_progress_proto_rawDescData []byte
)

func file_progress_proto_rawDescGZIP() []byte {
	file_progress_proto_rawDescOnce.Do(func() {
		file_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_progress_proto_rawDesc), len(file_progress_proto_rawDesc)))
	})
	return file_progress_proto_rawDescData
}

var file_progress_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_progress_proto_goTypes = []any{
	(ProgressType)(0),             // 0: desktop_server.v1.ProgressType
	(*StreamProgressRequest)(nil), // 1: desktop_server.v1.StreamProgressRequest
	(*ProgressUpdate)(nil),        // 2: desktop_server.v1.ProgressUpdate
}
var file_progress_proto_depIdxs = []int32{
	0, // 0: desktop_server.v1.ProgressUpdate.type:type_name -> desktop_server.v1.ProgressType
	1, // 1: desktop_server.v1.ProgressService.StreamDownloadProgress:input_type -> desktop_server.v1.StreamProgressRequest
	2, // 2: desktop_server.v1.ProgressService.StreamDownloadProgress:output_type -> desktop_server.v1.ProgressUpdate
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_progress_proto_init() }
func file_progress_proto_init() {
	if File_progress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_progress_proto_rawDesc), len(file_progress_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_progress_proto_goTypes,
		DependencyIndexes: file_progress_proto_depIdxs,
		EnumInfos:         file_progress_proto_enumTypes,
		MessageInfos:      file_progress_proto_msgTypes,
	}.Build()
	File_progress_proto = out.File
	file_progress_proto_goTypes = nil
	file_progress_proto_depIdxs = nil
}
