// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: progress.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProgressService_StreamDownloadProgress_FullMethodName = "/desktop_server.v1.ProgressService/StreamDownloadProgress"
)

// ProgressServiceClient is the client API for ProgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 進捗通知サービス
type ProgressServiceClient interface {
	// ダウンロード進捗をストリーミング
	StreamDownloadProgress(ctx context.Context, in *StreamProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressUpdate], error)
}

type progressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProgressServiceClient(cc grpc.ClientConnInterface) ProgressServiceClient {
	return &progressServiceClient{cc}
}

func (c *progressServiceClient) StreamDownloadProgress(ctx context.Context, in *StreamProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProgressService_ServiceDesc.Streams[0], ProgressService_StreamDownloadProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamProgressRequest, ProgressUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProgressService_StreamDownloadProgressClient = grpc.ServerStreamingClient[ProgressUpdate]

// ProgressServiceServer is the server API for ProgressService service.
// All implementations must embed UnimplementedProgressServiceServer
// for forward compatibility.
//
// 進捗通知サービス
type ProgressServiceServer interface {
	// ダウンロード進捗をストリーミング
	StreamDownloadProgress(*StreamProgressRequest, grpc.ServerStreamingServer[ProgressUpdate]) error
	mustEmbedUnimplementedProgressServiceServer()
}

// UnimplementedProgressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgressServiceServer struct{}

func (UnimplementedProgressServiceServer) StreamDownloadProgress(*StreamProgressRequest, grpc.ServerStreamingServer[ProgressUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamDownloadProgress not implemented")
}
func (UnimplementedProgressServiceServer) mustEmbedUnimplementedProgressServiceServer() {}
func (UnimplementedProgressServiceServer) testEmbeddedByValue()                         {}

// UnsafeProgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgressServiceServer will
// result in compilation errors.
type UnsafeProgressServiceServer interface {
	mustEmbedUnimplementedProgressServiceServer()
}

func RegisterProgressServiceServer(s grpc.ServiceRegistrar, srv ProgressServiceServer) {
	// If the following call pancis, it indicates UnimplementedProgressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProgressService_ServiceDesc, srv)
}

func _ProgressService_StreamDownloadProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProgressServiceServer).StreamDownloadProgress(m, &grpc.GenericServerStream[StreamProgressRequest, ProgressUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProgressService_StreamDownloadProgressServer = grpc.ServerStreamingServer[ProgressUpdate]

// ProgressService_ServiceDesc is the grpc.ServiceDesc for ProgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "desktop_server.v1.ProgressService",
	HandlerType: (*ProgressServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDownloadProgress",
			Handler:       _ProgressService_StreamDownloadProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "progress.proto",
}
